---
- name: "Validate that Cruise Control is running"
  ansible.builtin.include_role:
    name: amq_streams_common
    tasks_from: validation/service.yml
  vars:
    service_name: "{{ amq_streams_cruise_control_service_name }}"
