---
- name: "Automate AMQ Streams install"
  hosts: all
  vars:
    topic_name: myTopic
  roles:
    - role: amq_streams_install
  tasks:

    - name: "Ensures topic {{ topic_name }} exist."
      ansible.builtin.include_role:
        name: amq_streams_install
        tasks_from: topic/create.yml

    - name: "Describe created topic."
      ansible.builtin.include_role:
        name: amq_streams_install
        tasks_from: topic/describe.yml
